before_install:
- uname -a
- 'echo ''gem: --no-document'' > ~/.gemrc'
- gem update --system
- bundle config build.nokogiri --use-system-libraries
env:
  matrix:
  - LANG=en_US.UTF-8
  global:
    secure: HT+zh9qu5KThif4+p2+/oeZqjYd7nazoBEBgRZrwXR/2DwXEqFUf+XdzGGz/EeJ6lXgWL0+G4W69/dmdGF4JvJ5Fhap1sso2tGW5L+eq3MmaE4o1PGtriknSEXNnAAmG9ciwYE04KM0jRar6KbSHNO9UwZBareYWHD0Jtc7cJpc=
install:
- bundle install --path=vendor/bundle --without=development --binstubs --jobs=2 --retry=3
language: ruby
notifications:
  email:
    on_failure: change
    on_success: change
    recipients:
    - travis@jitter.eu
rvm:
- 2.1.5
script: bundle exec rake -q test
services: 
