before_install:
- uname -a
- 'echo ''gem: --no-document'' > ~/.gemrc'
- gem update --system
- bundle config build.nokogiri --use-system-libraries
env:
  matrix:
  - RACK_ENV=test LANG=en_US.UTF-8
  global:
  - secure: PlQKfXILwBQQCmK3n/NUg/c0Mt+2eWCy+WII7OWcyowG4btvX9Tl1BTWiBVNyO9Jj41LuG7B28Sn3yQPTPil1FNRzaoNTkW1fcjDg3GEv4QiwoqUdLENvDBhfXPDxXpbnhIDJFXWc9WxhvfZm68CEet8/jcCD/KWsvTz9kb0UXA=
  - secure: fiiAFa8p9pMuM3c9EZ+nb+lYv+CG1mQpPqSeqkMB6u1UBGNOpEoVJi/G//OVtoajDww3J3QvCqMeC5qF84gfsZLQCLRhjak2ne29ztS8x0H5fvz0v85aHbZHL0HwzEosrn0TZiKGHstm9EVe1hAh9/uMrUG1QlQB1OHbjJ88tFc=
  - secure: MyLdxaNPFLzBhJ/VxBhn+XU6J2dXx96X6fs4SEAb5Lv7UPVnDKSFLM4DNGFidhtYmlx2pONybs8HJmv3FODubET4nt40BQXkJ6vzYIRc2BLSLdARx+cJdiEWLSqDYLW3ffJSyUXEMuwhrjwD57oD4FvxMKy4CNeLL28kOnmV7dE=
install:
- bundle install --path vendor/bundle --without development --binstubs --retry 2
language: ruby
notifications:
  email:
    on_failure: change
    on_success: change
    recipients:
    - travis@jitter.eu
rvm:
- 2.1.5
script: bundle exec rake test
services: 
