before_install:
- uname -a
- 'echo ''gem: --no-document'' > ~/.gemrc'
- gem update --system
- bundle config build.nokogiri --use-system-libraries
env:
  matrix:
  - LANG=en_US.UTF-8
  global:
  - secure: Y2Wbr0VFhAXvuGv3IMGHODvpFCABWLXDFoWzBbx/FT/urPwSnaV9+wPIaw1OFSUioHYdnqAxDUscIuzqjo7Dh6jnb1aRVilZrk8Xxn9OlEEFnmBlKXlpmxANNt9klntRsqERL3JjNtBuxlPOFcOwkdWqOOnM66r02lesAnGIvAc=
  - secure: cqaBkqbD+s647i4aHwLjscVY1EboH9xYpvnYj8tZXlqNxiLiIwuBUf4u1VBgEyFFAgHbH6sf5htlCSJhhu9tK3o1U9gved1NeZ6qf76WqfDqb43lYcidanNqKm//XCRoVO8WkkGY9jdjDhM5PzKBOWM/yGvqBb6yq+56G2trDjk=
  - secure: lL/A9IOv6LYdQMKrrC+PtN++ZsB+HuxIJDt0b4E1h4FJuRKiWOHHPfGIlcmNcfMmXPXYhvDdA+DKST5a4w2lgyFEhwetuFcqSU+3bpKFEWzmRzrxq+HPm0xHuymVb3CRzpacd+xpdozH1XO5HRqcm/BLaXFS/r6c1Sgp/Dh+g9I=
install:
- bundle install --path=vendor/bundle --without=development --binstubs --jobs=2 --retry=3
language: ruby
notifications:
  email:
    on_failure: change
    on_success: change
    recipients:
    - travis@jitter.eu
rvm:
- 2.1.5
script: bundle exec rake -q test
services: 
