before_install:
- uname -a
- 'echo ''gem: --no-document'' > ~/.gemrc'
- gem update --system
- bundle config build.nokogiri --use-system-libraries
env:
  matrix:
  - LANG=en_US.UTF-8
  global:
    secure: LUEc6YR0xQEE/SC6DmhRVQZtxYN7XoBjzdtNd9k5moT0fV7JIPcUU7WcvNUimGPGixb65RaYeDXsXzRD7g9qaMLCx0nkEF+c4ML+dfqdEciivnGs0mvqFOLgcqboDOj2fizFYQHC8Luq7Y8JtXgbFwgZerFtDHxt89OH3mmjung=
install:
- bundle install --path=vendor/bundle --without=development --binstubs --jobs=2 --retry=3
language: ruby
notifications:
  email:
    on_failure: change
    on_success: change
    recipients:
    - travis@jitter.eu
rvm:
- 2.1.5
script: bundle exec rake -q test
services: 
