before_install:
- uname -a
- 'echo ''gem: --no-document'' > ~/.gemrc'
- gem update --system
- bundle config build.nokogiri --use-system-libraries
env:
  matrix:
  - LANG=en_US.UTF-8
  global:
    secure: Te7sjVETtbjQqJ+oiBvAgnWssix/w5mAaz99pRgS3fx3lGqhUArUOLwU2rcNEcvpHkXhMLjT4++8H5xcwtxqc5Z6aodwvkc6IFQCnvc2pYO4FArPTgzkOkNUgbs/Qr/02BNJ/ARcA0VQY6fvFstN+zkGrxJRG0K9iMmzari8mQ0=
install:
- bundle install --path=vendor/bundle --without=development --binstubs --jobs=2 --retry=3
language: ruby
notifications:
  email:
    on_failure: change
    on_success: change
    recipients:
    - travis@jitter.eu
rvm:
- 2.1.5
script: bundle exec rake -q test
services:
