:email:
  :to: "devop@managing.that.mess.org"
  :from: "ec2-user@scale.like.hell.com"
  :via: :smtp
  :via_options:
    :port: 25
    :enable_starttls_auto: false
    :authentication: :plain
    :address: "mail.google.com"
:email_template: "scale_report_email.erb"
:ruleset: "gradual_tail.rb"
:tables:
  - "casino_app"
  - "cash_flow"
  - "market_shares"
:group_downscales: true
:flush_after: 3600
:minimum_throughput: 1
:maximum_throughput: 20000
:update_alarms: true
