# example config file for use in the testing suite.

:logger:
  :level: INFO
  :sync:  true
  :style: pretty

:tables:
  - "dummy, just keeping the config loader happy"

:dry_run: true # use mockup provisioning data
