:aws:
  :region: "us-east-1"
:logger:
  :pretty: true
  :level: INFO
  :sync: true
:ruleset: "default.rb"
:tables:
  - "my_table1"
  - "my_table2"
# :dry_run: true
# :group_downscales: true
# :flush_after: 3600
# :minimum_throughput: 10
# :maximum_throughput: 20000
